//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozaikaApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MozaikaApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;cascade type_id=&quot;opencv-cascade-classifier&quot;&gt;&lt;stageType&gt;BOOST&lt;/stageType&gt;
        ///  &lt;featureType&gt;HAAR&lt;/featureType&gt;
        ///  &lt;height&gt;20&lt;/height&gt;
        ///  &lt;width&gt;20&lt;/width&gt;
        ///  &lt;stageParams&gt;
        ///    &lt;maxWeakCount&gt;109&lt;/maxWeakCount&gt;&lt;/stageParams&gt;
        ///  &lt;featureParams&gt;
        ///    &lt;maxCatCount&gt;0&lt;/maxCatCount&gt;&lt;/featureParams&gt;
        ///  &lt;stageNum&gt;20&lt;/stageNum&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;maxWeakCount&gt;3&lt;/maxWeakCount&gt;
        ///      &lt;stageThreshold&gt;3.5069230198860168e-01&lt;/stageThreshold&gt;
        ///      &lt;weakClassifiers&gt;
        ///      [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string haarcascade_frontalface_alt2 {
            get {
                return ResourceManager.GetString("haarcascade_frontalface_alt2", resourceCulture);
            }
        }
    }
}
